"""Domain-level persistence contracts consumed by KURAL services."""

from collections.abc import Iterator
from contextlib import AbstractContextManager
from datetime import datetime
from typing import Any, Protocol

from kural.cases.models import CallbackRequest, SupportCase
from kural.conversation.session import Conversation
from kural.models import State


class RepositoryTransaction(Protocol):
    def create_session(self, session_id: str, customer_ref: str, state: State) -> Conversation: ...
    def get_session(self, session_id: str) -> Conversation | None: ...
    def update_state(self, session_id: str, state: State) -> None: ...
    def add_turn(self, session_id: str, turn_order: int, text: str, intent: str,
                 state: State, response: str, outcome: str) -> None: ...
    def add_audit_event(self, session_id: str, event_type: str, state: State | None,
                        metadata: dict[str, Any]) -> None: ...
    def create_case(self, session_id: str, customer_ref: str, category: str,
                    description: str, status: str) -> SupportCase: ...
    def request_callback(self, session_id: str, case_id: str | None,
                         requested_at: datetime | None = None) -> CallbackRequest: ...


class KuralRepository(Protocol):
    def transaction(self) -> AbstractContextManager[RepositoryTransaction]: ...
    def health_check(self) -> None: ...
    def get_session(self, session_id: str) -> Conversation | None: ...
    def get_session_detail(self, session_id: str) -> dict[str, Any] | None: ...
    def list_cases(self) -> list[dict[str, Any]]: ...
    def list_callbacks(self, session_id: str | None = None) -> list[dict[str, Any]]: ...
    def list_audit_events(self, session_id: str) -> list[dict[str, Any]]: ...

