import { Waveform, FileCode, FileText, ShieldCheck, WarningCircle } from "@phosphor-icons/react";
import { useEffect, useState } from "react";
import { dashboardApi } from "../services/dashboardApi";
import { formatDateTime } from "../services/selectors";
import type { AuditEvent, CallRecord, Role } from "../types";
import { Drawer } from "./Drawer";
import { StatusPill } from "./StatusPill";

type DetailTab = "transcript" | "extraction" | "audit";
export function CallDetailDrawer({ call, role, onClose }: { call: CallRecord; role: Role; onClose: () => void }) {
  const [tab, setTab] = useState<DetailTab>("transcript");
  const [viewEvent, setViewEvent] = useState<AuditEvent | null>(null);
  useEffect(() => { void dashboardApi.recordAudit("TRANSCRIPT_VIEW", "CALL", call.id, role, "Call detail opened; transcript rendered").then(setViewEvent); }, [call.id, role]);
  const transcript = call.transcript.map((item) => ({ ...item, text: item.redacted ? item.text.replace(/\d{3,}/g, "[REDACTED]") : item.text }));
  return <Drawer title={call.id} eyebrow="CALL DETAIL · SYNTHETIC RECORD" onClose={onClose} wide>
    <div className="ops-detail-meta"><span>{call.customerRef}</span><span>{call.maskedPhone}</span><span>{formatDateTime(call.startedAt)} IST</span><StatusPill value={call.disposition ?? call.status} /></div>
    <div className="ops-detail-summary"><div><small>CAMPAIGN</small><strong>{call.campaignName}</strong></div><div><small>LANGUAGE</small><strong>{call.language}</strong></div><div><small>DURATION</small><strong>{Math.floor(call.durationSec / 60)}m {call.durationSec % 60}s</strong></div><div><small>APP</small><strong>{call.appInstalled ? `${call.appVersion}${call.appUpdated ? " · Updated" : " · Update available"}` : "Not installed"}</strong></div></div>
    <div className="ops-detail-tabbar" role="tablist" aria-label="Call details">{(["transcript", "extraction", "audit"] as const).map((item) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item === "transcript" ? <><FileText size={15} />Transcript &amp; recording</> : item === "extraction" ? <><FileCode size={15} />Structured data</> : <><ShieldCheck size={15} />Consent &amp; audit</>}</button>)}</div>
    {tab === "transcript" && <div className="ops-detail-grid"><section className="ops-detail-panel"><h3>Synced transcript <span>IST</span></h3><div className="ops-transcript">{transcript.map((message) => <article key={message.id}><time>{new Intl.DateTimeFormat("en-IN", { timeZone: "Asia/Kolkata", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(message.time))}</time><div><strong>{message.speaker === "AVA" ? "AVA" : "CUSTOMER"}</strong><p className={message.redacted ? "ops-redacted-text" : ""}>{message.text}{message.redacted && <em> · redacted</em>}</p></div></article>)}</div></section><section className="ops-detail-panel"><h3>Call recording <span>LOCAL DEMO</span></h3><div className="ops-audio-wave" aria-hidden="true">{Array.from({ length: 64 }, (_, index) => <i key={index} style={{ height: `${9 + ((index * 13 + index % 7 * 9) % 33)}px` }} />)}</div><div className="ops-audio-state"><Waveform size={17} /><span>Recording not included in synthetic call data.</span></div><button className="ops-button ops-button-secondary" disabled aria-disabled="true">Playback unavailable</button><p className="ops-helper">No customer audio is stored or played in this prototype. A real recording view must be permission-checked and audit-logged by the backend.</p></section></div>}
    {tab === "extraction" && <div className="ops-detail-grid"><section className="ops-detail-panel"><h3>Structured extraction</h3><pre className="ops-json">{JSON.stringify({ callId: call.id, intent: call.intent, disposition: call.disposition, appInstalled: call.appInstalled, appVersion: call.appVersion, appUpdated: call.appUpdated, sentiment: call.sentiment, issueCategory: call.issueCategory, featureInterest: call.featureInterest, policyDecision: call.policy }, null, 2)}</pre></section><section className="ops-detail-panel"><h3>KURAL decision timeline</h3><ol className="ops-decision-timeline">{["DISCLOSURE", "IDENTITY_CHECK", "PERMISSION", "APP_STATUS", call.kuralState].map((state, index) => <li key={`${state}-${index}`}><i /><span><strong>{state.replaceAll("_", " ")}</strong><small>{index === 4 ? <StatusPill value={call.policy} /> : "State transition · demo record"}</small></span></li>)}</ol></section></div>}
    {tab === "audit" && <div className="ops-detail-grid"><section className="ops-detail-panel"><h3>Consent record</h3><div className="ops-consent-row"><ShieldCheck size={19} /><div><strong>{call.consented ? "Purpose consent recorded" : "Consent not recorded"}</strong><span>Purpose: mobile app service call · Channel: voice</span></div><StatusPill value={call.consented ? "CONSENTED" : "BLOCKED"} /></div><div className="ops-fact-list"><span>Customer reference <strong>{call.customerRef}</strong></span><span>Recording coverage <strong>Not captured in demo</strong></span><span>Retention <strong>Demo policy · no audio retained</strong></span></div></section><section className="ops-detail-panel"><h3>Access audit</h3><div className="ops-audit-row"><WarningCircle size={16} /><span><strong>Transcript viewed</strong><small>{viewEvent ? `${viewEvent.actor} · ${formatDateTime(viewEvent.timestamp)} IST · local demo audit` : "Logging view event…"}</small></span></div><p className="ops-helper">Mock audit entries are browser-local and mutable. Production audit requires append-only server-side storage with authenticated actor and network metadata.</p></section></div>}
  </Drawer>;
}

