import { useState } from "react";
import { ArrowUpRight, WarningCircle } from "@phosphor-icons/react";
import { PageHeading } from "../components/PageHeading";
import { PageState } from "../components/PageState";
import { StatusPill } from "../components/StatusPill";
import { useDashboard } from "../hooks/DashboardContext";
import { useRole } from "../hooks/useRole";
import { dashboardApi } from "../services/dashboardApi";
import { formatDateTime } from "../services/selectors";
import type { CaseStatus } from "../types";

const columns: Array<{status:CaseStatus;label:string}> = [{status:"NEW",label:"New"},{status:"ASSIGNED",label:"Assigned"},{status:"IN_PROGRESS",label:"In progress"},{status:"RESOLVED",label:"Resolved"}];
export function EscalationsPage(){const {snapshot,loading,error,refresh}=useDashboard();const [role]=useRole();const [notice,setNotice]=useState("");if(!snapshot)return <PageState loading={loading} error={error} onRetry={()=>void refresh()}/>;
 async function move(id:string,status:CaseStatus){await dashboardApi.updateCase(id,{status,firstContactAt:status==="IN_PROGRESS"?new Date().toISOString():undefined,resolvedAt:status==="RESOLVED"?new Date().toISOString():null});await dashboardApi.recordAudit("CASE_STATUS_CHANGED","CASE",id,role,`Status set to ${status}`);await refresh();setNotice("Case status updated and synced successfully.");}
 async function assign(id:string,agentId:string){await dashboardApi.updateCase(id,{assignedAgentId:agentId||null,status:agentId?"ASSIGNED":"NEW"});await dashboardApi.recordAudit("CASE_ASSIGNED","CASE",id,role,agentId||"Unassigned");await refresh();}
 return <><PageHeading eyebrow="HUMAN FOLLOW-UP" title="Escalations" description="Explicit case lifecycle, ownership and SLA visibility across the support queue." actions={<span className="ops-mini-label"><WarningCircle size={15}/>{snapshot.escalations.filter(x=>x.status!=="RESOLVED"&&new Date(x.slaDueAt)<new Date()).length} SLA at risk</span>}/>{notice&&<div className="ops-notice-banner" role="status">{notice}<button onClick={()=>setNotice("")}>Dismiss</button></div>}
 <div className="ops-kanban">{columns.map(col=>{const items=snapshot.escalations.filter(item=>item.status===col.status);return <section className="ops-kanban-column" key={col.status}><header><strong>{col.label}</strong><span>{items.length}</span></header>{items.slice(0,100).map(item=><article className="ops-case-card" key={item.id}><div className="ops-case-card-top"><StatusPill value={item.priority}/><small>{item.id}</small></div><h3>{item.customerRef}<small>{item.maskedPhone}</small></h3><p>{item.issueSummary}</p><div className="ops-case-card-meta"><StatusPill value={item.severity}/><span>SLA {formatDateTime(item.slaDueAt)} IST</span></div><div className="ops-case-card-meta"><span>{item.category} · {item.preferredLanguage}</span><a href={`/call-log?query=${encodeURIComponent(item.callId)}`} aria-label={`Open call ${item.callId}`}>{item.callId}<ArrowUpRight size={13}/></a></div>{role!=="AGENT"&&<label className="ops-assign-select"><select aria-label={`Assign case ${item.id}`} value={item.assignedAgentId??""} onChange={e=>void assign(item.id,e.target.value)}><option value="">Unassigned</option>{snapshot.agents.map(agent=><option key={agent.id} value={agent.id}>{agent.name} · {agent.availability.toLowerCase()}</option>)}</select></label>}{col.status!=="RESOLVED"&&<div className="ops-case-card-actions"><button className="ops-button ops-button-secondary" onClick={()=>void move(item.id,col.status==="NEW"?"ASSIGNED":col.status==="ASSIGNED"?"IN_PROGRESS":"RESOLVED")}>{col.status==="IN_PROGRESS"?"Resolve case":"Move forward"}</button></div>}</article>)}</section>})}</div><p className="ops-table-note">Case assignment and status changes are audited under banking security policy.</p></>}
